### ISSUE TITLE
Class 'Engagespot\EngagespotPush' not found

### ISSUE THREAD

**Issue by Stitpragya** [Engagespot/Push-PHP-SDK#1]
I am using yii2 and composer 
directory got installed in vendor folder successfully..
but I got error..
Class 'Engagespot\EngagespotPush' not found
I cant give the correct path to use it

**Comment by anandrmedia** [comment]
Sorry, we were not actively monitoring issues on Github.
You just need to use the class \Engagespot\EngagespotPush. That will solve the problem.
